package com.example.inventory.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFFFF4081)  // Bright pink
val md_theme_light_onPrimary = Color(0xFF000000)  // Black text
val md_theme_light_primaryContainer = Color(0xFFFF80AB)  // Light pink
val md_theme_light_onPrimaryContainer = Color(0xFF000000)  // Black text
val md_theme_light_secondary = Color(0xFFF50057)  // Vibrant pink
val md_theme_light_onSecondary = Color(0xFF000000)  // Black text
val md_theme_light_secondaryContainer = Color(0xFFFF80AB)  // Light pink
val md_theme_light_onSecondaryContainer = Color(0xFF000000)  // Black text
val md_theme_light_tertiary = Color(0xFFF06292)  // Soft pink
val md_theme_light_onTertiary = Color(0xFF000000)  // Black text
val md_theme_light_tertiaryContainer = Color(0xFFFFCDD2)  // Very light pink
val md_theme_light_onTertiaryContainer = Color(0xFF000000)  // Black text
val md_theme_light_error = Color(0xFFD50000)  // Bright red for error
val md_theme_light_errorContainer = Color(0xFFFFCDD2)  // Light pink for error container
val md_theme_light_onError = Color(0xFF000000)  // Black text
val md_theme_light_onErrorContainer = Color(0xFF000000)  // Black text
val md_theme_light_background = Color(0xFFFFEBEE)  // Light pink background
val md_theme_light_onBackground = Color(0xFF000000)  // Black text
val md_theme_light_surface = Color(0xFFFFEBEE)  // Light pink surface
val md_theme_light_onSurface = Color(0xFF000000)  // Black text
val md_theme_light_surfaceVariant = Color(0xFFF8BBD0)  // Soft pink variant
val md_theme_light_onSurfaceVariant = Color(0xFF000000)  // Black text
val md_theme_light_outline = Color(0xFFF8BBD0)  // Soft pink outline
val md_theme_light_inverseOnSurface = Color(0xFF000000)  // Black text for inverse surface
val md_theme_light_inverseSurface = Color(0xFFFFEBEE)  // Light pink for inverse surface
val md_theme_light_inversePrimary = Color(0xFFFF4081)  // Bright pink for inverse primary
val md_theme_light_surfaceTint = Color(0xFFFF4081)  // Bright pink tint
val md_theme_light_outlineVariant = Color(0xFFF8BBD0)  // Soft pink variant outline
val md_theme_light_scrim = Color(0xFF000000)  // Black scrim

val md_theme_dark_primary = Color(0xFFFF80AB)  // Light pink
val md_theme_dark_onPrimary = Color(0xFF000000)  // Black text
val md_theme_dark_primaryContainer = Color(0xFFFF4081)  // Bright pink
val md_theme_dark_onPrimaryContainer = Color(0xFF000000)  // Black text
val md_theme_dark_secondary = Color(0xFFF50057)  // Vibrant pink
val md_theme_dark_onSecondary = Color(0xFF000000)  // Black text
val md_theme_dark_secondaryContainer = Color(0xFFFF80AB)  // Light pink
val md_theme_dark_onSecondaryContainer = Color(0xFF000000)  // Black text
val md_theme_dark_tertiary = Color(0xFFF06292)  // Soft pink
val md_theme_dark_onTertiary = Color(0xFF000000)  // Black text
val md_theme_dark_tertiaryContainer = Color(0xFFFFCDD2)  // Very light pink
val md_theme_dark_onTertiaryContainer = Color(0xFF000000)  // Black text
val md_theme_dark_error = Color(0xFFD50000)  // Bright red for error
val md_theme_dark_errorContainer = Color(0xFFFFCDD2)  // Light pink for error container
val md_theme_dark_onError = Color(0xFF000000)  // Black text
val md_theme_dark_onErrorContainer = Color(0xFF000000)  // Black text
val md_theme_dark_background = Color(0xFF880E4F)  // Dark pink background
val md_theme_dark_onBackground = Color(0xFFFFFFFF)  // White text
val md_theme_dark_surface = Color(0xFF880E4F)  // Dark pink surface
val md_theme_dark_onSurface = Color(0xFFFFFFFF)  // White text
val md_theme_dark_surfaceVariant = Color(0xFFF8BBD0)  // Soft pink variant
val md_theme_dark_onSurfaceVariant = Color(0xFF000000)  // Black text
val md_theme_dark_outline = Color(0xFFF8BBD0)  // Soft pink outline
val md_theme_dark_inverseOnSurface = Color(0xFF000000)  // Black text for inverse surface
val md_theme_dark_inverseSurface = Color(0xFFFFEBEE)  // Light pink for inverse surface
val md_theme_dark_inversePrimary = Color(0xFFFF4081)  // Bright pink for inverse primary
val md_theme_dark_surfaceTint = Color(0xFFFF80AB)  // Light pink tint
val md_theme_dark_outlineVariant = Color(0xFFF8BBD0)  // Soft pink variant outline
val md_theme_dark_scrim = Color(0xFF000000)  // Black scrim
